# Do not forget to create the .env file (see template)
# before using this container!

services:
    collector:
        restart: always
        build: .
        environment:
            PORT: 8080
        ports:
            - $PORT:8080
